Vid 38 cleanup
edvinasstaupas/videoteka pull request #10
Opened 2023-05-11 18:42 UTC by Mantas330BJ

2023-05-11 18:45 UTC, gzili approved these changes

2023-05-12 17:51 UTC, edvinasstaupas requested changes

2023-05-12 17:51 UTC, edvinasstaupas commented on backend/src/main/java/com/videolibrary/backend/infrastructure/rest/controller/MoviesController.java
this is the default value, since its the only value specified, why write it verbosely?

2023-05-12 17:51 UTC, edvinasstaupas commented on backend/src/main/java/com/videolibrary/backend/infrastructure/rest/controller/MoviesController.java
> +@RequestMapping(path = "movies")
I like plural version for endpoints as well, but rest specifies that endpoints should be singular. See here: https://petstore.swagger.io/

2023-05-12 20:06 UTC, Mantas330BJ commented on backend/src/main/java/com/videolibrary/backend/infrastructure/rest/controller/MoviesController.java
> +@RequestMapping(path = "movies")
Accidentally wrote it verbosely when experimented with headers

2023-05-12 20:08 UTC, Mantas330BJ commented on backend/src/main/java/com/videolibrary/backend/infrastructure/rest/controller/MoviesController.java
> +@RequestMapping(path = "movies")
I think that plurals are more logical and are more common. Having /movie return all movies is slightly counterintuitive

https://blog.dreamfactory.com/best-practices-for-naming-rest-api-endpoints/

2023-05-12 20:10 UTC, Mantas330BJ commented on backend/src/main/java/com/videolibrary/backend/domain/service/FileStorageService.java
Interesting. Never heard of that before

2023-05-12 20:14 UTC, edvinasstaupas commented on backend/src/main/java/com/videolibrary/backend/domain/service/FileStorageService.java
Thats a structure that we use at my job. I am open to any other structures you suggest. 
My arguments are that this makes clear what is the purpose of the part.

2023-05-12 20:14 UTC, Mantas330BJ commented on backend/src/main/java/com/videolibrary/backend/infrastructure/rest/controller/SeriesController.java
> +@RequestMapping(path = "series")
Fixed

2023-05-12 20:16 UTC, Mantas330BJ commented on backend/src/main/java/com/videolibrary/backend/domain/service/FileStorageService.java
Moved to infrastructure

2023-05-12 20:16 UTC, edvinasstaupas commented on backend/src/main/java/com/videolibrary/backend/infrastructure/rest/controller/MoviesController.java
> +@RequestMapping(path = "movies")
I concur about the paths. Whole REST idea is quite lenient and so we can leave it like this.

2023-05-12 20:17 UTC, edvinasstaupas approved these changes

2023-05-12 20:17 UTC, merged